import { PrismaClient } from '@prisma/client';
import { encrypt, hashPassword } from '../src/lib/crypto';

const prisma = new PrismaClient();

// Sample patients data
const patients = [
  {
    id: 'P001',
    password_hash: null,
    name_enc: 'Karthik Rajan',
    dob_enc: '1985-03-15',
    gender_enc: 'Male',
    contact_enc: '9876543210',
    mobile_enc: '9876543210',
    email_enc: 'karthik.rajan@email.com',
    address_enc: '123, Gandhi Street, T. Nagar',
    city_enc: 'Chennai',
    district_enc: 'Chennai',
    state_enc: 'Tamil Nadu',
    pincode_enc: '600017',
    guardian_name_enc: null,
    emergency_name_enc: 'Lakshmi Rajan',
    emergency_relation_enc: 'Spouse',
    emergency_phone_enc: '9876543211',
    occupation_enc: 'Software Engineer',
    marital_status_enc: 'Married',
    preferred_language_enc: 'Tamil',
    insurance_provider_enc: 'Star Health Insurance',
    insurance_policy_enc: 'SHI-2024-789456',
    aadhaar_last4_enc: '1234',
    blood_type_enc: 'O+',
    allergies_enc: 'Penicillin',
    chronic_conditions_enc: 'Hypertension, Type 2 Diabetes',
    current_medications_enc: 'Metformin 500mg, Amlodipine 5mg',
    past_surgeries_enc: 'Appendectomy (2010)',
    family_history_enc: 'Father: Hypertension, Mother: Diabetes',
    lifestyle_notes_enc: 'Smoker (10 cigarettes/day), Moderate alcohol consumption',
    consent_emergency: true,
    consent_specialist: true,
    consent_research: false,
    abha_id_enc: '91-1234-5678-9012',
  },
  {
    id: 'P002',
    password_hash: null,
    name_enc: 'Priya Sharma',
    dob_enc: '1990-07-22',
    gender_enc: 'Female',
    contact_enc: '9876543212',
    mobile_enc: '9876543212',
    email_enc: 'priya.sharma@email.com',
    address_enc: '45, Nehru Road, Anna Nagar',
    city_enc: 'Chennai',
    district_enc: 'Chennai',
    state_enc: 'Tamil Nadu',
    pincode_enc: '600040',
    guardian_name_enc: null,
    emergency_name_enc: 'Rahul Sharma',
    emergency_relation_enc: 'Husband',
    emergency_phone_enc: '9876543213',
    occupation_enc: 'Teacher',
    marital_status_enc: 'Married',
    preferred_language_enc: 'Tamil',
    insurance_provider_enc: 'ICICI Lombard',
    insurance_policy_enc: 'ICICI-2024-456789',
    aadhaar_last4_enc: '5678',
    blood_type_enc: 'A+',
    allergies_enc: 'Sulfa drugs',
    chronic_conditions_enc: 'Asthma',
    current_medications_enc: 'Albuterol inhaler as needed',
    past_surgeries_enc: 'C-section (2018)',
    family_history_enc: 'Mother: Asthma, Father: None',
    lifestyle_notes_enc: 'Non-smoker, Regular yoga practitioner',
    consent_emergency: true,
    consent_specialist: true,
    consent_research: true,
    abha_id_enc: '91-2345-6789-0123',
  },
  {
    id: 'P003',
    password_hash: null,
    name_enc: 'Ramesh Kumar',
    dob_enc: '1978-11-08',
    gender_enc: 'Male',
    contact_enc: '9876543214',
    mobile_enc: '9876543214',
    email_enc: 'ramesh.kumar@email.com',
    address_enc: '78, Mount Road, Chennai',
    city_enc: 'Chennai',
    district_enc: 'Chennai',
    state_enc: 'Tamil Nadu',
    pincode_enc: '600002',
    guardian_name_enc: null,
    emergency_name_enc: 'Sunita Kumar',
    emergency_relation_enc: 'Sister',
    emergency_phone_enc: '9876543215',
    occupation_enc: 'Business Owner',
    marital_status_enc: 'Single',
    preferred_language_enc: 'Tamil',
    insurance_provider_enc: 'HDFC Ergo',
    insurance_policy_enc: 'HDFC-2024-123456',
    aadhaar_last4_enc: '9012',
    blood_type_enc: 'B+',
    allergies_enc: 'None known',
    chronic_conditions_enc: 'Hyperlipidemia',
    current_medications_enc: 'Atorvastatin 20mg',
    past_surgeries_enc: 'Knee arthroscopy (2015)',
    family_history_enc: 'Father: Heart disease, Mother: Hyperlipidemia',
    lifestyle_notes_enc: 'Non-smoker, Occasional alcohol',
    consent_emergency: true,
    consent_specialist: false,
    consent_research: false,
    abha_id_enc: '91-3456-7890-1234',
  },
  {
    id: 'P004',
    password_hash: null,
    name_enc: 'Anitha Devi',
    dob_enc: '1995-02-14',
    gender_enc: 'Female',
    contact_enc: '9876543216',
    mobile_enc: '9876543216',
    email_enc: 'anitha.devi@email.com',
    address_enc: '56, Beach Road, Besant Nagar',
    city_enc: 'Chennai',
    district_enc: 'Chennai',
    state_enc: 'Tamil Nadu',
    pincode_enc: '600090',
    guardian_name_enc: null,
    emergency_name_enc: 'Venkat Devi',
    emergency_relation_enc: 'Father',
    emergency_phone_enc: '9876543217',
    occupation_enc: 'Software Developer',
    marital_status_enc: 'Single',
    preferred_language_enc: 'English',
    insurance_provider_enc: 'Bajaj Allianz',
    insurance_policy_enc: 'BAJAJ-2024-789012',
    aadhaar_last4_enc: '3456',
    blood_type_enc: 'AB+',
    allergies_enc: 'Dust mites',
    chronic_conditions_enc: 'None',
    current_medications_enc: 'None',
    past_surgeries_enc: 'None',
    family_history_enc: 'Mother: Thyroid disorder',
    lifestyle_notes_enc: 'Non-smoker, Vegetarian, Regular exercise',
    consent_emergency: true,
    consent_specialist: true,
    consent_research: true,
    abha_id_enc: '91-4567-8901-2345',
  },
  {
    id: 'P005',
    password_hash: null,
    name_enc: 'Suresh Babu',
    dob_enc: '1965-09-30',
    gender_enc: 'Male',
    contact_enc: '9876543218',
    mobile_enc: '9876543218',
    email_enc: 'suresh.babu@email.com',
    address_enc: '89, LIC Colony, Adyar',
    city_enc: 'Chennai',
    district_enc: 'Chennai',
    state_enc: 'Tamil Nadu',
    pincode_enc: '600020',
    guardian_name_enc: null,
    emergency_name_enc: 'Meena Babu',
    emergency_relation_enc: 'Spouse',
    emergency_phone_enc: '9876543219',
    occupation_enc: 'Retired Bank Manager',
    marital_status_enc: 'Married',
    preferred_language_enc: 'Tamil',
    insurance_provider_enc: 'National Insurance',
    insurance_policy_enc: 'NI-2024-345678',
    aadhaar_last4_enc: '7890',
    blood_type_enc: 'A-',
    allergies_enc: 'Aspirin',
    chronic_conditions_enc: 'Coronary Artery Disease, Hypertension',
    current_medications_enc: 'Aspirin 81mg, Metoprolol 25mg, Lisinopril 10mg',
    past_surgeries_enc: 'CABG (2019)',
    family_history_enc: 'Father: Heart disease, Brother: Diabetes',
    lifestyle_notes_enc: 'Ex-smoker (quit 2019), Low sodium diet',
    consent_emergency: true,
    consent_specialist: true,
    consent_research: false,
    abha_id_enc: '91-5678-9012-3456',
  },
  {
    id: 'P006',
    password_hash: null,
    name_enc: 'Divya Lakshmi',
    dob_enc: '1988-05-18',
    gender_enc: 'Female',
    contact_enc: '9876543220',
    mobile_enc: '9876543220',
    email_enc: 'divya.lakshmi@email.com',
    address_enc: '23, Velachery Main Road',
    city_enc: 'Chennai',
    district_enc: 'Chennai',
    state_enc: 'Tamil Nadu',
    pincode_enc: '600042',
    guardian_name_enc: null,
    emergency_name_enc: 'Karthik Lakshmi',
    emergency_relation_enc: 'Brother',
    emergency_phone_enc: '9876543221',
    occupation_enc: 'Nurse',
    marital_status_enc: 'Single',
    preferred_language_enc: 'Tamil',
    insurance_provider_enc: 'Religare Health Insurance',
    insurance_policy_enc: 'RHI-2024-567890',
    aadhaar_last4_enc: '2345',
    blood_type_enc: 'O+',
    allergies_enc: 'Latex',
    chronic_conditions_enc: 'Migraine',
    current_medications_enc: 'Sumatriptan as needed',
    past_surgeries_enc: 'None',
    family_history_enc: 'Mother: Migraine, Father: None',
    lifestyle_notes_enc: 'Non-smoker, Regular sleep schedule',
    consent_emergency: true,
    consent_specialist: true,
    consent_research: true,
    abha_id_enc: '91-6789-0123-4567',
  },
  {
    id: 'P007',
    password_hash: null,
    name_enc: 'Vijay Kumar',
    dob_enc: '1992-12-05',
    gender_enc: 'Male',
    contact_enc: '9876543222',
    mobile_enc: '9876543222',
    email_enc: 'vijay.kumar@email.com',
    address_enc: '67, OMR Road, Perungudi',
    city_enc: 'Chennai',
    district_enc: 'Chennai',
    state_enc: 'Tamil Nadu',
    pincode_enc: '600096',
    guardian_name_enc: null,
    emergency_name_enc: 'Kavitha Kumar',
    emergency_relation_enc: 'Spouse',
    emergency_phone_enc: '9876543223',
    occupation_enc: 'IT Consultant',
    marital_status_enc: 'Married',
    preferred_language_enc: 'English',
    insurance_provider_enc: 'Apollo Munich',
    insurance_policy_enc: 'AM-2024-901234',
    aadhaar_last4_enc: '6789',
    blood_type_enc: 'B+',
    allergies_enc: 'None known',
    chronic_conditions_enc: 'None',
    current_medications_enc: 'None',
    past_surgeries_enc: 'None',
    family_history_enc: 'Father: None, Mother: None',
    lifestyle_notes_enc: 'Non-smoker, Regular gym goer',
    consent_emergency: true,
    consent_specialist: true,
    consent_research: true,
    abha_id_enc: '91-7890-1234-5678',
  },
  {
    id: 'P008',
    password_hash: null,
    name_enc: 'Kavitha Rajan',
    dob_enc: '1987-08-25',
    gender_enc: 'Female',
    contact_enc: '9876543224',
    mobile_enc: '9876543224',
    email_enc: 'kavitha.rajan@email.com',
    address_enc: '34, Kodambakkam High Road',
    city_enc: 'Chennai',
    district_enc: 'Chennai',
    state_enc: 'Tamil Nadu',
    pincode_enc: '600024',
    guardian_name_enc: null,
    emergency_name_enc: 'Rajesh Rajan',
    emergency_relation_enc: 'Father',
    emergency_phone_enc: '9876543225',
    occupation_enc: 'Accountant',
    marital_status_enc: 'Married',
    preferred_language_enc: 'Tamil',
    insurance_provider_enc: 'Max Bupa',
    insurance_policy_enc: 'MB-2024-234567',
    aadhaar_last4_enc: '0123',
    blood_type_enc: 'A+',
    allergies_enc: 'Peanuts',
    chronic_conditions_enc: 'Hypothyroidism',
    current_medications_enc: 'Levothyroxine 50mcg',
    past_surgeries_enc: 'None',
    family_history_enc: 'Mother: Hypothyroidism, Father: None',
    lifestyle_notes_enc: 'Non-smoker, Gluten-free diet',
    consent_emergency: true,
    consent_specialist: false,
    consent_research: false,
    abha_id_enc: '91-8901-2345-6789',
  },
  {
    id: 'P009',
    password_hash: null,
    name_enc: 'Arun Prakash',
    dob_enc: '1980-04-10',
    gender_enc: 'Male',
    contact_enc: '9876543226',
    mobile_enc: '9876543226',
    email_enc: 'arun.prakash@email.com',
    address_enc: '12, Sterling Road, Nungambakkam',
    city_enc: 'Chennai',
    district_enc: 'Chennai',
    state_enc: 'Tamil Nadu',
    pincode_enc: '600034',
    guardian_name_enc: null,
    emergency_name_enc: 'Shanti Prakash',
    emergency_relation_enc: 'Spouse',
    emergency_phone_enc: '9876543227',
    occupation_enc: 'Civil Engineer',
    marital_status_enc: 'Married',
    preferred_language_enc: 'Tamil',
    insurance_provider_enc: 'Star Health Insurance',
    insurance_policy_enc: 'SHI-2024-345678',
    aadhaar_last4_enc: '4567',
    blood_type_enc: 'O-',
    allergies_enc: 'None known',
    chronic_conditions_enc: 'Gout',
    current_medications_enc: 'Allopurinol 300mg',
    past_surgeries_enc: 'None',
    family_history_enc: 'Father: Gout, Mother: None',
    lifestyle_notes_enc: 'Non-smoker, Low purine diet',
    consent_emergency: true,
    consent_specialist: true,
    consent_research: true,
    abha_id_enc: '91-9012-3456-7890',
  },
  {
    id: 'P010',
    password_hash: null,
    name_enc: 'Meena Sundaram',
    dob_enc: '1975-06-20',
    gender_enc: 'Female',
    contact_enc: '9876543228',
    mobile_enc: '9876543228',
    email_enc: 'meena.sundaram@email.com',
    address_enc: '56, Ashok Nagar',
    city_enc: 'Chennai',
    district_enc: 'Chennai',
    state_enc: 'Tamil Nadu',
    pincode_enc: '600083',
    guardian_name_enc: null,
    emergency_name_enc: 'Sundaram Rajan',
    emergency_relation_enc: 'Husband',
    emergency_phone_enc: '9876543229',
    occupation_enc: 'Homemaker',
    marital_status_enc: 'Married',
    preferred_language_enc: 'Tamil',
    insurance_provider_enc: 'ICICI Lombard',
    insurance_policy_enc: 'ICICI-2024-678901',
    aadhaar_last4_enc: '8901',
    blood_type_enc: 'B+',
    allergies_enc: 'None known',
    chronic_conditions_enc: 'Osteoarthritis',
    current_medications_enc: 'Celecoxib 200mg as needed',
    past_surgeries_enc: 'Hysterectomy (2012)',
    family_history_enc: 'Mother: Osteoarthritis, Father: None',
    lifestyle_notes_enc: 'Non-smoker, Light physical activity',
    consent_emergency: true,
    consent_specialist: true,
    consent_research: false,
    abha_id_enc: '91-0123-4567-8901',
  },
];

// Sample doctors data - 3 doctors per hospital
const doctors = [
  // Apollo Hospital
  {
    id: 'dr_arun',
    password_hash: hashPassword('doctor123'),
    full_name_enc: 'Dr. Arun Prakash',
    gender_enc: 'Male',
    dob_enc: '1979-04-12',
    mobile_enc: '9876543236',
    email_enc: 'arun.prakash@apollo.com',
    registration_number: 'TNMC34567',
    registration_council: 'Tamil Nadu Medical Council',
    registration_year: '2007',
    qualification_enc: 'MBBS, MD (Neurology)',
    specialty: 'Neurology',
    department: 'Neurology',
    designation: 'Senior Neurologist',
    hospital: 'Apollo Hospital',
    experience_years: 17,
    languages_json: JSON.stringify(['Tamil', 'English', 'Telugu']),
    consultation_modes_json: JSON.stringify(['In-person', 'Teleconsult']),
    available_days_json: JSON.stringify(['Mon', 'Wed', 'Fri']),
    time_slots_json: JSON.stringify(['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM']),
    room_number_enc: 'NEU-101',
    address_enc: '67, OMR Road, Perungudi, Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600096',
    status: 'active',
  },
  {
    id: 'dr_kavitha',
    password_hash: hashPassword('doctor123'),
    full_name_enc: 'Dr. Kavitha Sundaram',
    gender_enc: 'Female',
    dob_enc: '1984-09-22',
    mobile_enc: '9876543237',
    email_enc: 'kavitha.sundaram@apollo.com',
    registration_number: 'TNMC34568',
    registration_council: 'Tamil Nadu Medical Council',
    registration_year: '2013',
    qualification_enc: 'MBBS, MD (Gynecology)',
    specialty: 'Gynecology',
    department: 'Gynecology',
    designation: 'Senior Gynecologist',
    hospital: 'Apollo Hospital',
    experience_years: 11,
    languages_json: JSON.stringify(['Tamil', 'English']),
    consultation_modes_json: JSON.stringify(['In-person', 'Teleconsult']),
    available_days_json: JSON.stringify(['Tue', 'Thu', 'Sat']),
    time_slots_json: JSON.stringify(['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM']),
    room_number_enc: 'GYN-201',
    address_enc: '34, Kodambakkam High Road, Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600024',
    status: 'active',
  },
  {
    id: 'dr_suresh',
    password_hash: hashPassword('doctor123'),
    full_name_enc: 'Dr. Suresh Babu',
    gender_enc: 'Male',
    dob_enc: '1976-06-30',
    mobile_enc: '9876543238',
    email_enc: 'suresh.babu@apollo.com',
    registration_number: 'TNMC34569',
    registration_council: 'Tamil Nadu Medical Council',
    registration_year: '2005',
    qualification_enc: 'MBBS, MS (Ophthalmology)',
    specialty: 'Ophthalmology',
    department: 'Ophthalmology',
    designation: 'Senior Ophthalmologist',
    hospital: 'Apollo Hospital',
    experience_years: 19,
    languages_json: JSON.stringify(['Tamil', 'English', 'Kannada']),
    consultation_modes_json: JSON.stringify(['In-person']),
    available_days_json: JSON.stringify(['Mon', 'Tue', 'Wed', 'Thu', 'Fri']),
    time_slots_json: JSON.stringify(['09:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '02:00 PM', '03:00 PM']),
    room_number_enc: 'OPHT-301',
    address_enc: '12, sterling Road, Nungambakkam, Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600034',
    status: 'active',
  },

  // Kauvery Hospital
  {
    id: 'dr_venkat',
    password_hash: hashPassword('doctor123'),
    full_name_enc: 'Dr. Venkat Subramanian',
    gender_enc: 'Male',
    dob_enc: '1978-12-10',
    mobile_enc: '9876543232',
    email_enc: 'venkat.subramanian@kauvery.com',
    registration_number: 'TNMC12347',
    registration_council: 'Tamil Nadu Medical Council',
    registration_year: '2006',
    qualification_enc: 'MBBS, MD (General Medicine)',
    specialty: 'General Medicine',
    department: 'General Medicine',
    designation: 'Senior Physician',
    hospital: 'Kauvery Hospital',
    experience_years: 18,
    languages_json: JSON.stringify(['Tamil', 'English', 'Telugu']),
    consultation_modes_json: JSON.stringify(['In-person']),
    available_days_json: JSON.stringify(['Mon', 'Tue', 'Wed', 'Thu', 'Fri']),
    time_slots_json: JSON.stringify(['09:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '02:00 PM', '03:00 PM']),
    room_number_enc: 'GM-301',
    address_enc: '78, Mount Road, Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600002',
    status: 'active',
  },
  {
    id: 'dr_priya',
    password_hash: hashPassword('doctor123'),
    full_name_enc: 'Dr. Priya Lakshmanan',
    gender_enc: 'Female',
    dob_enc: '1985-03-25',
    mobile_enc: '9876543233',
    email_enc: 'priya.lakshmanan@kauvery.com',
    registration_number: 'TNMC23456',
    registration_council: 'Tamil Nadu Medical Council',
    registration_year: '2012',
    qualification_enc: 'MBBS, MD (Pediatrics)',
    specialty: 'Pediatrics',
    department: 'Pediatrics',
    designation: 'Senior Pediatrician',
    hospital: 'Kauvery Hospital',
    experience_years: 12,
    languages_json: JSON.stringify(['Tamil', 'English']),
    consultation_modes_json: JSON.stringify(['In-person', 'Teleconsult']),
    available_days_json: JSON.stringify(['Mon', 'Wed', 'Fri']),
    time_slots_json: JSON.stringify(['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM']),
    room_number_enc: 'PED-101',
    address_enc: '56, Beach Road, Besant Nagar, Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600090',
    status: 'active',
  },
  {
    id: 'dr_ramesh',
    password_hash: hashPassword('doctor123'),
    full_name_enc: 'Dr. Ramesh Krishnan',
    gender_enc: 'Male',
    dob_enc: '1980-07-18',
    mobile_enc: '9876543234',
    email_enc: 'ramesh.krishnan@kauvery.com',
    registration_number: 'TNMC23457',
    registration_council: 'Tamil Nadu Medical Council',
    registration_year: '2008',
    qualification_enc: 'MBBS, MS (Orthopedics)',
    specialty: 'Orthopedics',
    department: 'Orthopedics',
    designation: 'Senior Orthopedic Surgeon',
    hospital: 'Kauvery Hospital',
    experience_years: 16,
    languages_json: JSON.stringify(['Tamil', 'English', 'Malayalam']),
    consultation_modes_json: JSON.stringify(['In-person']),
    available_days_json: JSON.stringify(['Tue', 'Thu', 'Sat']),
    time_slots_json: JSON.stringify(['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM']),
    room_number_enc: 'ORT-201',
    address_enc: '89, LIC Colony, Adyar, Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600020',
    status: 'active',
  },

  // Govt Hospital
  {
    id: 'dr_dhanush',
    password_hash: hashPassword('doctor123'),
    full_name_enc: 'Dr. Dhanush',
    gender_enc: 'Male',
    dob_enc: '1980-05-15',
    mobile_enc: '9876543230',
    email_enc: 'dhanush@govt.gov.in',
    registration_number: 'TNMC12345',
    registration_council: 'Tamil Nadu Medical Council',
    registration_year: '2008',
    qualification_enc: 'MBBS, MD (Emergency Medicine)',
    specialty: 'Emergency Medicine',
    department: 'Emergency',
    designation: 'Senior Emergency Physician',
    hospital: 'Govt Hospital',
    experience_years: 16,
    languages_json: JSON.stringify(['Tamil', 'English', 'Hindi']),
    consultation_modes_json: JSON.stringify(['In-person', 'Teleconsult']),
    available_days_json: JSON.stringify(['Mon', 'Wed', 'Fri']),
    time_slots_json: JSON.stringify(['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM', '04:00 PM']),
    room_number_enc: 'ER-101',
    address_enc: '123, Gandhi Street, T. Nagar, Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600017',
    status: 'active',
  },
  {
    id: 'dr_monissha',
    password_hash: hashPassword('doctor123'),
    full_name_enc: 'Dr. Monissha',
    gender_enc: 'Female',
    dob_enc: '1982-08-20',
    mobile_enc: '9876543231',
    email_enc: 'monissha@govt.gov.in',
    registration_number: 'TNMC12346',
    registration_council: 'Tamil Nadu Medical Council',
    registration_year: '2010',
    qualification_enc: 'MBBS, MD (Cardiology)',
    specialty: 'Cardiology',
    department: 'Cardiology',
    designation: 'Senior Cardiologist',
    hospital: 'Govt Hospital',
    experience_years: 14,
    languages_json: JSON.stringify(['Tamil', 'English']),
    consultation_modes_json: JSON.stringify(['In-person', 'Teleconsult']),
    available_days_json: JSON.stringify(['Tue', 'Thu', 'Sat']),
    time_slots_json: JSON.stringify(['09:00 AM', '10:00 AM', '11:00 AM', '02:00 PM', '03:00 PM']),
    room_number_enc: 'CARD-201',
    address_enc: '45, Nehru Road, Anna Nagar, Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600040',
    status: 'active',
  },
  {
    id: 'dr_anita',
    password_hash: hashPassword('doctor123'),
    full_name_enc: 'Dr. Anita Desai',
    gender_enc: 'Female',
    dob_enc: '1983-11-05',
    mobile_enc: '9876543235',
    email_enc: 'anita.desai@govt.gov.in',
    registration_number: 'TNMC23458',
    registration_council: 'Tamil Nadu Medical Council',
    registration_year: '2011',
    qualification_enc: 'MBBS, MD (Dermatology)',
    specialty: 'Dermatology',
    department: 'Dermatology',
    designation: 'Senior Dermatologist',
    hospital: 'Govt Hospital',
    experience_years: 13,
    languages_json: JSON.stringify(['Tamil', 'English', 'Hindi']),
    consultation_modes_json: JSON.stringify(['In-person', 'Teleconsult']),
    available_days_json: JSON.stringify(['Mon', 'Tue', 'Wed', 'Thu', 'Fri']),
    time_slots_json: JSON.stringify(['09:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '02:00 PM']),
    room_number_enc: 'DERM-301',
    address_enc: '23, Velachery Main Road, Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600042',
    status: 'active',
  },
];

// Longitudinal medical records for each patient
const medicalRecords = [
  // P001 - Karthik Rajan (Hypertension, Diabetes)
  {
    patient_id: 'P001',
    date: '2020-01-15',
    type_enc: 'Routine Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Essential Hypertension',
    notes_enc: 'Patient presents with elevated BP readings. Started antihypertensive medication.',
    lab_results_enc: 'BP: 150/95 mmHg, Fasting Glucose: 126 mg/dL, HbA1c: 6.8%',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Amlodipine 5mg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 150, "bp_diastolic": 95, "heart_rate": 78, "temp": 98.6}',
    follow_up_date: '2020-02-15',
  },
  {
    patient_id: 'P001',
    date: '2020-06-10',
    type_enc: 'Follow-up Visit',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Type 2 Diabetes Mellitus',
    notes_enc: 'Blood glucose levels elevated. Started Metformin therapy.',
    lab_results_enc: 'Fasting Glucose: 142 mg/dL, Postprandial: 198 mg/dL, HbA1c: 7.2%',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Amlodipine 5mg, Metformin 500mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 142, "bp_diastolic": 88, "heart_rate": 76, "temp": 98.4}',
    follow_up_date: '2020-09-10',
  },
  {
    patient_id: 'P001',
    date: '2021-03-20',
    type_enc: 'Annual Health Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Hypertension, Diabetes - Controlled',
    notes_enc: 'BP and glucose levels well controlled. Continue current medications.',
    lab_results_enc: 'BP: 132/82 mmHg, Fasting Glucose: 110 mg/dL, HbA1c: 6.4%, Lipid Panel: Normal',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Amlodipine 5mg, Metformin 500mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 132, "bp_diastolic": 82, "heart_rate": 74, "temp": 98.6}',
    follow_up_date: '2021-06-20',
  },
  {
    patient_id: 'P001',
    date: '2022-08-15',
    type_enc: 'Emergency Visit',
    provider_enc: 'Dr. Dhanush (ER Attending)',
    diagnosis_enc: 'Acute Bronchitis',
    notes_enc: 'Patient presented with severe cough and fever. Treated with antibiotics and bronchodilators.',
    lab_results_enc: 'WBC: 12,500, Chest X-ray: Clear, SpO2: 96%',
    department_enc: 'Emergency',
    doctor_name_enc: 'Dr. Dhanush',
    medications_enc: 'Azithromycin 500mg, Albuterol inhaler',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 138, "bp_diastolic": 85, "heart_rate": 92, "temp": 101.2, "spo2": 96}',
    follow_up_date: '2022-08-22',
  },
  {
    patient_id: 'P001',
    date: '2023-05-10',
    type_enc: 'Cardiology Follow-up',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Hypertension, Diabetes - Well Controlled',
    notes_enc: 'Excellent control of chronic conditions. Continue current regimen.',
    lab_results_enc: 'BP: 128/80 mmHg, Fasting Glucose: 98 mg/dL, HbA1c: 6.1%, ECG: Normal',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Amlodipine 5mg, Metformin 500mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 128, "bp_diastolic": 80, "heart_rate": 72, "temp": 98.4}',
    follow_up_date: '2023-11-10',
  },
  {
    patient_id: 'P001',
    date: '2024-01-20',
    type_enc: 'Routine Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Hypertension, Diabetes - Stable',
    notes_enc: 'Patient reports good adherence to medications. Lifestyle modifications discussed.',
    lab_results_enc: 'BP: 130/82 mmHg, Fasting Glucose: 105 mg/dL, HbA1c: 6.3%, Creatinine: 1.1 mg/dL',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Amlodipine 5mg, Metformin 500mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 130, "bp_diastolic": 82, "heart_rate": 75, "temp": 98.6}',
    follow_up_date: '2024-07-20',
  },

  // P002 - Priya Sharma (Asthma)
  {
    patient_id: 'P002',
    date: '2019-04-12',
    type_enc: 'Initial Consultation',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Bronchogenic Asthma',
    notes_enc: 'Patient presents with recurrent wheezing and shortness of breath. Started on inhaled corticosteroids.',
    lab_results_enc: 'Spirometry: FEV1 72% predicted, Allergy panel: Dust mites positive',
    department_enc: 'Pulmonology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Fluticasone/Salmeterol 100/50mcg twice daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 118, "bp_diastolic": 72, "heart_rate": 80, "temp": 98.4, "spo2": 97}',
    follow_up_date: '2019-07-12',
  },
  {
    patient_id: 'P002',
    date: '2020-02-20',
    type_enc: 'Follow-up Visit',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Asthma - Controlled',
    notes_enc: 'Symptoms well controlled. Continue current inhaler therapy.',
    lab_results_enc: 'Spirometry: FEV1 85% predicted, Peak Flow: 420 L/min',
    department_enc: 'Pulmonology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Fluticasone/Salmeterol 100/50mcg twice daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 115, "bp_diastolic": 70, "heart_rate": 76, "temp": 98.6, "spo2": 98}',
    follow_up_date: '2020-08-20',
  },
  {
    patient_id: 'P002',
    date: '2021-09-15',
    type_enc: 'Emergency Visit',
    provider_enc: 'Dr. Dhanush (ER Attending)',
    diagnosis_enc: 'Acute Asthma Exacerbation',
    notes_enc: 'Severe asthma attack triggered by viral infection. Treated with nebulization and steroids.',
    lab_results_enc: 'SpO2: 88%, WBC: 11,200, Chest X-ray: Hyperinflation',
    department_enc: 'Emergency',
    doctor_name_enc: 'Dr. Dhanush',
    medications_enc: 'Albuterol nebulization, Prednisone 40mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 125, "bp_diastolic": 78, "heart_rate": 110, "temp": 99.8, "spo2": 88}',
    follow_up_date: '2021-09-22',
  },
  {
    patient_id: 'P002',
    date: '2022-05-10',
    type_enc: 'Pulmonology Follow-up',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Asthma - Improved',
    notes_enc: 'Post-exacerbation recovery good. Increased inhaled steroid dose.',
    lab_results_enc: 'Spirometry: FEV1 80% predicted, Peak Flow: 400 L/min',
    department_enc: 'Pulmonology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Fluticasone/Salmeterol 250/50mcg twice daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 120, "bp_diastolic": 74, "heart_rate": 78, "temp": 98.4, "spo2": 97}',
    follow_up_date: '2022-11-10',
  },
  {
    patient_id: 'P002',
    date: '2023-12-01',
    type_enc: 'Annual Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Asthma - Well Controlled',
    notes_enc: 'Excellent control achieved. Consider step-down therapy.',
    lab_results_enc: 'Spirometry: FEV1 90% predicted, Peak Flow: 450 L/min',
    department_enc: 'Pulmonology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Fluticasone/Salmeterol 100/50mcg twice daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 116, "bp_diastolic": 70, "heart_rate": 74, "temp": 98.6, "spo2": 99}',
    follow_up_date: '2024-06-01',
  },

  // P003 - Ramesh Kumar (Hyperlipidemia)
  {
    patient_id: 'P003',
    date: '2018-07-20',
    type_enc: 'Health Screening',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Hyperlipidemia',
    notes_enc: 'Routine screening reveals elevated cholesterol. Started statin therapy.',
    lab_results_enc: 'Total Cholesterol: 285 mg/dL, LDL: 185 mg/dL, HDL: 38 mg/dL, Triglycerides: 310 mg/dL',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Atorvastatin 20mg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 135, "bp_diastolic": 82, "heart_rate": 76, "temp": 98.6}',
    follow_up_date: '2018-10-20',
  },
  {
    patient_id: 'P003',
    date: '2019-04-15',
    type_enc: 'Follow-up Visit',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Hyperlipidemia - Improving',
    notes_enc: 'Lipid levels improving. Continue statin therapy.',
    lab_results_enc: 'Total Cholesterol: 220 mg/dL, LDL: 140 mg/dL, HDL: 42 mg/dL, Triglycerides: 190 mg/dL',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Atorvastatin 20mg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 132, "bp_diastolic": 80, "heart_rate": 74, "temp": 98.4}',
    follow_up_date: '2019-10-15',
  },
  {
    patient_id: 'P003',
    date: '2020-11-10',
    type_enc: 'Orthopedic Consultation',
    provider_enc: 'Dr. Sharma (Orthopedics)',
    diagnosis_enc: 'Meniscal Tear - Left Knee',
    notes_enc: 'Knee pain and swelling. MRI confirms meniscal tear. Arthroscopic repair performed.',
    lab_results_enc: 'MRI: Medial meniscus tear, X-ray: Normal',
    department_enc: 'Orthopedics',
    doctor_name_enc: 'Dr. Sharma',
    medications_enc: 'Ibuprofen 400mg, Atorvastatin 20mg',
    procedures_enc: 'Knee Arthroscopy',
    vitals_json_enc: '{"bp_systolic": 130, "bp_diastolic": 78, "heart_rate": 72, "temp": 98.6}',
    follow_up_date: '2020-12-10',
  },
  {
    patient_id: 'P003',
    date: '2021-06-20',
    type_enc: 'Post-operative Follow-up',
    provider_enc: 'Dr. Sharma (Orthopedics)',
    diagnosis_enc: 'Knee Recovery - Excellent',
    notes_enc: 'Excellent recovery from arthroscopy. Full range of motion restored.',
    lab_results_enc: 'Physical Exam: Normal knee function',
    department_enc: 'Orthopedics',
    doctor_name_enc: 'Dr. Sharma',
    medications_enc: 'Atorvastatin 20mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 128, "bp_diastolic": 76, "heart_rate": 70, "temp": 98.4}',
    follow_up_date: '2022-06-20',
  },
  {
    patient_id: 'P003',
    date: '2023-03-15',
    type_enc: 'Cardiology Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Hyperlipidemia - Controlled',
    notes_enc: 'Lipid levels well controlled. Continue current therapy.',
    lab_results_enc: 'Total Cholesterol: 195 mg/dL, LDL: 115 mg/dL, HDL: 48 mg/dL, Triglycerides: 160 mg/dL',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Atorvastatin 20mg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 126, "bp_diastolic": 74, "heart_rate": 72, "temp": 98.6}',
    follow_up_date: '2023-09-15',
  },

  // P004 - Anitha Devi (No chronic conditions)
  {
    patient_id: 'P004',
    date: '2021-02-10',
    type_enc: 'Routine Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'General Health - Normal',
    notes_enc: 'Annual health checkup. All parameters within normal limits.',
    lab_results_enc: 'CBC: Normal, Lipid Panel: Normal, Thyroid: Normal, BP: 118/72 mmHg',
    department_enc: 'General Medicine',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'None',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 118, "bp_diastolic": 72, "heart_rate": 72, "temp": 98.4}',
    follow_up_date: '2022-02-10',
  },
  {
    patient_id: 'P004',
    date: '2022-08-20',
    type_enc: 'Dermatology Consultation',
    provider_enc: 'Dr. Patel (Dermatology)',
    diagnosis_enc: 'Allergic Contact Dermatitis',
    notes_enc: 'Skin rash on arms. Patch test positive for nickel. Avoid nickel-containing items.',
    lab_results_enc: 'Patch Test: Nickel positive',
    department_enc: 'Dermatology',
    doctor_name_enc: 'Dr. Patel',
    medications_enc: 'Hydrocortisone cream 1%',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 115, "bp_diastolic": 70, "heart_rate": 70, "temp": 98.6}',
    follow_up_date: '2022-09-20',
  },
  {
    patient_id: 'P004',
    date: '2023-05-15',
    type_enc: 'Routine Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'General Health - Normal',
    notes_enc: 'Annual health checkup. All parameters normal. Dermatitis resolved.',
    lab_results_enc: 'CBC: Normal, Lipid Panel: Normal, BP: 116/70 mmHg',
    department_enc: 'General Medicine',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'None',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 116, "bp_diastolic": 70, "heart_rate": 68, "temp": 98.4}',
    follow_up_date: '2024-05-15',
  },

  // P005 - Suresh Babu (CAD, Hypertension)
  {
    patient_id: 'P005',
    date: '2018-03-10',
    type_enc: 'Cardiology Consultation',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Coronary Artery Disease',
    notes_enc: 'Patient presents with angina. Stress test positive. Started on cardiac medications.',
    lab_results_enc: 'Stress Test: Positive for ischemia, ECG: ST depression, Lipid Panel: Elevated',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Aspirin 81mg, Metoprolol 25mg, Lisinopril 10mg, Atorvastatin 40mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 145, "bp_diastolic": 90, "heart_rate": 82, "temp": 98.6}',
    follow_up_date: '2018-06-10',
  },
  {
    patient_id: 'P005',
    date: '2019-01-20',
    type_enc: 'Cardiac Catheterization',
    provider_enc: 'Dr. Sharma (Interventional Cardiology)',
    diagnosis_enc: 'Triple Vessel Disease',
    notes_enc: 'Coronary angiography reveals triple vessel disease. Referred for CABG.',
    lab_results_enc: 'Angiogram: 70% LAD, 80% RCA, 60% LCX stenosis',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Sharma',
    medications_enc: 'Aspirin 81mg, Metoprolol 25mg, Lisinopril 10mg, Atorvastatin 40mg',
    procedures_enc: 'Coronary Angiography',
    vitals_json_enc: '{"bp_systolic": 140, "bp_diastolic": 85, "heart_rate": 78, "temp": 98.4}',
    follow_up_date: '2019-02-20',
  },
  {
    patient_id: 'P005',
    date: '2019-04-15',
    type_enc: 'CABG Surgery',
    provider_enc: 'Dr. Kumar (Cardiac Surgery)',
    diagnosis_enc: 'Triple Vessel CAD',
    notes_enc: 'Successful CABG with 3 grafts. Post-operative recovery uneventful.',
    lab_results_enc: 'Post-op ECG: Normal, Echo: EF 55%',
    department_enc: 'Cardiac Surgery',
    doctor_name_enc: 'Dr. Kumar',
    medications_enc: 'Aspirin 81mg, Metoprolol 25mg, Lisinopril 10mg, Atorvastatin 40mg',
    procedures_enc: 'Coronary Artery Bypass Graft (CABG)',
    vitals_json_enc: '{"bp_systolic": 130, "bp_diastolic": 80, "heart_rate": 75, "temp": 98.6}',
    follow_up_date: '2019-07-15',
  },
  {
    patient_id: 'P005',
    date: '2020-10-20',
    type_enc: 'Post-CABG Follow-up',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Post-CABG - Stable',
    notes_enc: 'Excellent post-surgical recovery. No angina symptoms. Continue current medications.',
    lab_results_enc: 'Echo: EF 58%, Stress Test: Negative, Lipid Panel: Controlled',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Aspirin 81mg, Metoprolol 25mg, Lisinopril 10mg, Atorvastatin 40mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 125, "bp_diastolic": 78, "heart_rate": 72, "temp": 98.4}',
    follow_up_date: '2021-04-20',
  },
  {
    patient_id: 'P005',
    date: '2022-06-15',
    type_enc: 'Annual Cardiac Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Post-CABG - Excellent',
    notes_enc: 'Grafts patent. Excellent cardiac function. Continue current regimen.',
    lab_results_enc: 'Echo: EF 60%, Stress Test: Negative, BP: 122/76 mmHg',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Aspirin 81mg, Metoprolol 25mg, Lisinopril 10mg, Atorvastatin 40mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 122, "bp_diastolic": 76, "heart_rate": 70, "temp": 98.6}',
    follow_up_date: '2023-06-15',
  },
  {
    patient_id: 'P005',
    date: '2024-02-10',
    type_enc: 'Routine Cardiac Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Post-CABG - Stable',
    notes_enc: '5 years post-CABG. Stable condition. Continue current medications.',
    lab_results_enc: 'Echo: EF 58%, Lipid Panel: Normal, BP: 120/74 mmHg',
    department_enc: 'Cardiology',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Aspirin 81mg, Metoprolol 25mg, Lisinopril 10mg, Atorvastatin 40mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 120, "bp_diastolic": 74, "heart_rate": 68, "temp": 98.4}',
    follow_up_date: '2024-08-10',
  },

  // P006 - Divya Lakshmi (Migraine)
  {
    patient_id: 'P006',
    date: '2020-05-12',
    type_enc: 'Neurology Consultation',
    provider_enc: 'Dr. Reddy (Neurology)',
    diagnosis_enc: 'Migraine with Aura',
    notes_enc: 'Patient presents with recurrent headaches with visual aura. Started on prophylactic therapy.',
    lab_results_enc: 'MRI Brain: Normal, EEG: Normal',
    department_enc: 'Neurology',
    doctor_name_enc: 'Dr. Reddy',
    medications_enc: 'Topiramate 50mg daily, Sumatriptan as needed',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 112, "bp_diastolic": 68, "heart_rate": 72, "temp": 98.4}',
    follow_up_date: '2020-08-12',
  },
  {
    patient_id: 'P006',
    date: '2021-02-20',
    type_enc: 'Neurology Follow-up',
    provider_enc: 'Dr. Reddy (Neurology)',
    diagnosis_enc: 'Migraine - Improved',
    notes_enc: 'Headache frequency reduced. Continue current therapy.',
    lab_results_enc: 'Headache Diary: 2-3 attacks/month (down from 8-10)',
    department_enc: 'Neurology',
    doctor_name_enc: 'Dr. Reddy',
    medications_enc: 'Topiramate 50mg daily, Sumatriptan as needed',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 110, "bp_diastolic": 66, "heart_rate": 70, "temp": 98.6}',
    follow_up_date: '2021-08-20',
  },
  {
    patient_id: 'P006',
    date: '2022-09-15',
    type_enc: 'Neurology Checkup',
    provider_enc: 'Dr. Reddy (Neurology)',
    diagnosis_enc: 'Migraine - Well Controlled',
    notes_enc: 'Excellent control achieved. Consider reducing prophylactic dose.',
    lab_results_enc: 'Headache Diary: 1-2 attacks/month',
    department_enc: 'Neurology',
    doctor_name_enc: 'Dr. Reddy',
    medications_enc: 'Topiramate 25mg daily, Sumatriptan as needed',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 108, "bp_diastolic": 64, "heart_rate": 68, "temp": 98.4}',
    follow_up_date: '2023-03-15',
  },
  {
    patient_id: 'P006',
    date: '2023-11-20',
    type_enc: 'Annual Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Migraine - Controlled, General Health Normal',
    notes_enc: 'Migraine well controlled. All other parameters normal.',
    lab_results_enc: 'CBC: Normal, Lipid Panel: Normal, BP: 108/64 mmHg',
    department_enc: 'General Medicine',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Topiramate 25mg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 108, "bp_diastolic": 64, "heart_rate": 66, "temp": 98.6}',
    follow_up_date: '2024-05-20',
  },

  // P007 - Vijay Kumar (No chronic conditions)
  {
    patient_id: 'P007',
    date: '2021-06-10',
    type_enc: 'Pre-employment Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'General Health - Normal',
    notes_enc: 'Pre-employment health screening. All parameters within normal limits.',
    lab_results_enc: 'CBC: Normal, Lipid Panel: Normal, LFT: Normal, KFT: Normal, BP: 120/76 mmHg',
    department_enc: 'General Medicine',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'None',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 120, "bp_diastolic": 76, "heart_rate": 70, "temp": 98.4}',
    follow_up_date: '2022-06-10',
  },
  {
    patient_id: 'P007',
    date: '2022-12-15',
    type_enc: 'Sports Injury Consultation',
    provider_enc: 'Dr. Sharma (Orthopedics)',
    diagnosis_enc: 'Ankle Sprain - Grade 2',
    notes_enc: 'Ankle injury during basketball. RICE therapy prescribed. Full recovery expected.',
    lab_results_enc: 'X-ray: No fracture',
    department_enc: 'Orthopedics',
    doctor_name_enc: 'Dr. Sharma',
    medications_enc: 'Ibuprofen 400mg',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 118, "bp_diastolic": 74, "heart_rate": 72, "temp": 98.6}',
    follow_up_date: '2023-01-15',
  },
  {
    patient_id: 'P007',
    date: '2023-06-20',
    type_enc: 'Routine Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'General Health - Normal',
    notes_enc: 'Annual health checkup. All parameters normal. Ankle fully recovered.',
    lab_results_enc: 'CBC: Normal, Lipid Panel: Normal, BP: 118/74 mmHg',
    department_enc: 'General Medicine',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'None',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 118, "bp_diastolic": 74, "heart_rate": 68, "temp": 98.4}',
    follow_up_date: '2024-06-20',
  },

  // P008 - Kavitha Rajan (Hypothyroidism)
  {
    patient_id: 'P008',
    date: '2019-03-18',
    type_enc: 'Endocrinology Consultation',
    provider_enc: 'Dr. Gupta (Endocrinology)',
    diagnosis_enc: 'Hypothyroidism',
    notes_enc: 'Patient presents with fatigue, weight gain, cold intolerance. TSH elevated. Started on levothyroxine.',
    lab_results_enc: 'TSH: 12.5 mIU/L, Free T4: 0.8 ng/dL, Anti-TPO: Positive',
    department_enc: 'Endocrinology',
    doctor_name_enc: 'Dr. Gupta',
    medications_enc: 'Levothyroxine 50mcg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 122, "bp_diastolic": 76, "heart_rate": 68, "temp": 97.8}',
    follow_up_date: '2019-06-18',
  },
  {
    patient_id: 'P008',
    date: '2019-09-20',
    type_enc: 'Endocrinology Follow-up',
    provider_enc: 'Dr. Gupta (Endocrinology)',
    diagnosis_enc: 'Hypothyroidism - Improving',
    notes_enc: 'TSH levels improving. Increase levothyroxine dose.',
    lab_results_enc: 'TSH: 6.2 mIU/L, Free T4: 1.1 ng/dL',
    department_enc: 'Endocrinology',
    doctor_name_enc: 'Dr. Gupta',
    medications_enc: 'Levothyroxine 75mcg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 120, "bp_diastolic": 74, "heart_rate": 70, "temp": 98.4}',
    follow_up_date: '2020-03-20',
  },
  {
    patient_id: 'P008',
    date: '2020-10-15',
    type_enc: 'Endocrinology Checkup',
    provider_enc: 'Dr. Gupta (Endocrinology)',
    diagnosis_enc: 'Hypothyroidism - Controlled',
    notes_enc: 'TSH normalized. Continue current dose.',
    lab_results_enc: 'TSH: 2.8 mIU/L, Free T4: 1.3 ng/dL',
    department_enc: 'Endocrinology',
    doctor_name_enc: 'Dr. Gupta',
    medications_enc: 'Levothyroxine 75mcg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 118, "bp_diastolic": 72, "heart_rate": 72, "temp": 98.6}',
    follow_up_date: '2021-04-15',
  },
  {
    patient_id: 'P008',
    date: '2022-05-10',
    type_enc: 'Annual Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Hypothyroidism - Stable, General Health Normal',
    notes_enc: 'Thyroid function stable. All other parameters normal.',
    lab_results_enc: 'TSH: 3.1 mIU/L, Lipid Panel: Normal, BP: 116/72 mmHg',
    department_enc: 'General Medicine',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Levothyroxine 75mcg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 116, "bp_diastolic": 72, "heart_rate": 70, "temp": 98.4}',
    follow_up_date: '2023-05-10',
  },
  {
    patient_id: 'P008',
    date: '2023-12-01',
    type_enc: 'Endocrinology Checkup',
    provider_enc: 'Dr. Gupta (Endocrinology)',
    diagnosis_enc: 'Hypothyroidism - Well Controlled',
    notes_enc: 'Excellent control maintained. Continue current dose.',
    lab_results_enc: 'TSH: 2.5 mIU/L, Free T4: 1.2 ng/dL',
    department_enc: 'Endocrinology',
    doctor_name_enc: 'Dr. Gupta',
    medications_enc: 'Levothyroxine 75mcg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 114, "bp_diastolic": 70, "heart_rate": 68, "temp": 98.6}',
    follow_up_date: '2024-06-01',
  },

  // P009 - Arun Prakash (Gout)
  {
    patient_id: 'P009',
    date: '2020-07-25',
    type_enc: 'Rheumatology Consultation',
    provider_enc: 'Dr. Patel (Rheumatology)',
    diagnosis_enc: 'Gout',
    notes_enc: 'Patient presents with acute podagra. Uric acid elevated. Started on allopurinol.',
    lab_results_enc: 'Uric Acid: 9.2 mg/dL, CRP: 12 mg/L, Joint Aspiration: Urate crystals',
    department_enc: 'Rheumatology',
    doctor_name_enc: 'Dr. Patel',
    medications_enc: 'Allopurinol 300mg daily, Colchicine as needed',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 128, "bp_diastolic": 80, "heart_rate": 76, "temp": 99.2}',
    follow_up_date: '2020-10-25',
  },
  {
    patient_id: 'P009',
    date: '2021-02-20',
    type_enc: 'Rheumatology Follow-up',
    provider_enc: 'Dr. Patel (Rheumatology)',
    diagnosis_enc: 'Gout - Improving',
    notes_enc: 'Uric acid levels improving. No acute attacks. Continue allopurinol.',
    lab_results_enc: 'Uric Acid: 6.8 mg/dL, CRP: Normal',
    department_enc: 'Rheumatology',
    doctor_name_enc: 'Dr. Patel',
    medications_enc: 'Allopurinol 300mg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 124, "bp_diastolic": 76, "heart_rate": 72, "temp": 98.4}',
    follow_up_date: '2021-08-20',
  },
  {
    patient_id: 'P009',
    date: '2022-06-15',
    type_enc: 'Rheumatology Checkup',
    provider_enc: 'Dr. Patel (Rheumatology)',
    diagnosis_enc: 'Gout - Controlled',
    notes_enc: 'Uric acid at target level. No attacks for 1 year. Continue current therapy.',
    lab_results_enc: 'Uric Acid: 5.5 mg/dL, Lipid Panel: Normal',
    department_enc: 'Rheumatology',
    doctor_name_enc: 'Dr. Patel',
    medications_enc: 'Allopurinol 300mg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 122, "bp_diastolic": 74, "heart_rate": 70, "temp": 98.6}',
    follow_up_date: '2023-06-15',
  },
  {
    patient_id: 'P009',
    date: '2023-11-10',
    type_enc: 'Annual Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Gout - Controlled, General Health Normal',
    notes_enc: 'Gout well controlled. All other parameters normal.',
    lab_results_enc: 'Uric Acid: 5.2 mg/dL, Lipid Panel: Normal, BP: 120/74 mmHg',
    department_enc: 'General Medicine',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Allopurinol 300mg daily',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 120, "bp_diastolic": 74, "heart_rate": 68, "temp": 98.4}',
    follow_up_date: '2024-05-10',
  },

  // P010 - Meena Sundaram (Osteoarthritis)
  {
    patient_id: 'P010',
    date: '2018-04-20',
    type_enc: 'Gynecology Consultation',
    provider_enc: 'Dr. Sharma (Gynecology)',
    diagnosis_enc: 'Fibroid Uterus',
    notes_enc: 'Patient presents with menorrhagia and pelvic pain. Ultrasound confirms fibroids. Hysterectomy recommended.',
    lab_results_enc: 'Ultrasound: Multiple uterine fibroids, Hemoglobin: 10.2 g/dL',
    department_enc: 'Gynecology',
    doctor_name_enc: 'Dr. Sharma',
    medications_enc: 'Iron supplements, Tranexamic acid',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 130, "bp_diastolic": 82, "heart_rate": 78, "temp": 98.6}',
    follow_up_date: '2018-07-20',
  },
  {
    patient_id: 'P010',
    date: '2012-06-15',
    type_enc: 'Hysterectomy Surgery',
    provider_enc: 'Dr. Sharma (Gynecology)',
    diagnosis_enc: 'Fibroid Uterus',
    notes_enc: 'Successful total abdominal hysterectomy. Post-operative recovery uneventful.',
    lab_results_enc: 'Post-op Hb: 9.8 g/dL, Pathology: Benign leiomyomas',
    department_enc: 'Gynecology',
    doctor_name_enc: 'Dr. Sharma',
    medications_enc: 'Iron supplements, Analgesics',
    procedures_enc: 'Total Abdominal Hysterectomy',
    vitals_json_enc: '{"bp_systolic": 125, "bp_diastolic": 78, "heart_rate": 75, "temp": 98.8}',
    follow_up_date: '2012-09-15',
  },
  {
    patient_id: 'P010',
    date: '2020-09-10',
    type_enc: 'Orthopedic Consultation',
    provider_enc: 'Dr. Sharma (Orthopedics)',
    diagnosis_enc: 'Osteoarthritis - Knees',
    notes_enc: 'Patient presents with bilateral knee pain. X-ray confirms osteoarthritis. Started on symptomatic treatment.',
    lab_results_enc: 'X-ray: Grade 2 OA both knees, CRP: Normal',
    department_enc: 'Orthopedics',
    doctor_name_enc: 'Dr. Sharma',
    medications_enc: 'Celecoxib 200mg as needed, Calcium supplements',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 128, "bp_diastolic": 80, "heart_rate": 74, "temp": 98.4}',
    follow_up_date: '2021-03-10',
  },
  {
    patient_id: 'P010',
    date: '2021-10-20',
    type_enc: 'Orthopedic Follow-up',
    provider_enc: 'Dr. Sharma (Orthopedics)',
    diagnosis_enc: 'Osteoarthritis - Stable',
    notes_enc: 'Symptoms controlled with medication. Physical therapy recommended.',
    lab_results_enc: 'Physical Exam: Reduced range of motion both knees',
    department_enc: 'Orthopedics',
    doctor_name_enc: 'Dr. Sharma',
    medications_enc: 'Celecoxib 200mg as needed, Calcium supplements',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 126, "bp_diastolic": 78, "heart_rate": 72, "temp": 98.6}',
    follow_up_date: '2022-04-20',
  },
  {
    patient_id: 'P010',
    date: '2023-05-15',
    type_enc: 'Annual Checkup',
    provider_enc: 'Dr. Monissha (Cardiology)',
    diagnosis_enc: 'Osteoarthritis - Stable, General Health Normal',
    notes_enc: 'OA symptoms stable. All other parameters normal.',
    lab_results_enc: 'Lipid Panel: Normal, BP: 124/78 mmHg, Calcium: Normal',
    department_enc: 'General Medicine',
    doctor_name_enc: 'Dr. Monissha',
    medications_enc: 'Celecoxib 200mg as needed, Calcium supplements',
    procedures_enc: null,
    vitals_json_enc: '{"bp_systolic": 124, "bp_diastolic": 78, "heart_rate": 70, "temp": 98.4}',
    follow_up_date: '2024-05-15',
  },
];

async function main() {
  console.log('🌱 Starting database seed...');

  // Clear existing data
  console.log('🧹 Clearing existing data...');
  await prisma.auditLog.deleteMany();
  await prisma.clinicalAlert.deleteMany();
  await prisma.appointment.deleteMany();
  await prisma.chatMessage.deleteMany();
  await prisma.patientFile.deleteMany();
  await prisma.recordsOtp.deleteMany();
  await prisma.chatbotMessage.deleteMany();
  await prisma.chatbotConversation.deleteMany();
  await prisma.pushSubscription.deleteMany();
  await prisma.medicalRecord.deleteMany();
  await prisma.patient.deleteMany();
  await prisma.doctor.deleteMany();

  // Insert patients
  console.log('👥 Inserting patients...');
  for (const patient of patients) {
    await prisma.patient.create({
      data: patient,
    });
    console.log(`  ✅ Created patient: ${patient.id} - ${patient.name_enc}`);
  }

  // Insert doctors
  console.log('👨‍⚕️ Inserting doctors...');
  for (const doctor of doctors) {
    await prisma.doctor.create({
      data: doctor,
    });
    console.log(`  ✅ Created doctor: ${doctor.id} - ${doctor.full_name_enc} (${doctor.hospital})`);
  }

  // Insert medical records
  console.log('📋 Inserting medical records...');
  for (const record of medicalRecords) {
    await prisma.medicalRecord.create({
      data: record,
    });
    console.log(`  ✅ Created record for ${record.patient_id} on ${record.date}`);
  }

  console.log('✨ Seed completed successfully!');
  console.log(`📊 Summary: ${patients.length} patients, ${doctors.length} doctors, ${medicalRecords.length} medical records`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
